name: 'Pre-Release Zip Archive Create'

on:
  release:
    types: [prereleased]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      plugin_slug: ${{ github.event.repository.name }}

    steps:
      - name: Setup PHP with WP-CLI and Composer
        uses: shivammathur/setup-php@v2
        with:
          tools: wp,composer
          php-version: 8.2

      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          path: ${{ env.plugin_slug }}
          ref: ${{ github.ref }}

      - name: Config WP-CLI dist-archive-command
        run: wp package install wp-cli/dist-archive-command

      - name: Install Composer dependencies
        run: cd ${{ env.plugin_slug }} && composer install --no-dev

      - name: Install NPM dependencies
        run: cd ${{ env.plugin_slug }} && npm run build

      - name: Create Plugin Zip
        run: wp dist-archive ${{ env.plugin_slug }} --filename-format="{name}-{version}.zip"

      - name: Save Zip to Release
        uses: xresloader/upload-to-github-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: "*.zip"
          tags: true
